### ISSUE TITLE
Licencing clarification?

### ISSUE THREAD

**Issue by 1944GPW** [adisreyaj/angular-star-rating#3]
Hi,
  I'm looking at star ratings modules now, and yours looks sort of what I want.
What is the licence associated with your code? There is no mention that I can find anywhere in the files of whether it is open source, and if so, what restrictions you have it under. I need to be sure before using in an MIT-licenced project.
Regards

1944GPW.

**Comment by adisreyaj** [comment]
I will soon add the license....It will be MIT.
